lex_url: http://www.lexique.org/databases/Lexique383/Lexique383.tsv
lex_output: ./assets/lexique.csv
lex_error: ./dist/lex_errors.csv

bib_url: https://api.zotero.org/groups/6284894/items?format=csljson
bib_output: ./assets/bib.json

record_file: ../mastei-notes/dates.yml
tag_file: ../mastei-notes/dict.yml

nouns_output: ./assets/nouns.csv

tag_output: ./assets/tags.json
tag_match: ./dist/tag_match.csv

record_output: ./dist/records.json
